version: '3.8'

services:
  mywebsite:
    build:
      context: /home/ubuntu/dev/sum_excel_project/
      dockerfile: Dockerfile
    container_name: sum_excel_container
    ports:
      - "8000:8000"
    networks:
      - sum_excel

networks:
  sum_excel:
    driver: bridge
